### ISSUE TITLE
在安装好一个php的情况，继续安装php8报错

### ISSUE THREAD

**Issue by 449134904** [oneinstack/oneinstack#339]
![图片](https://user-images.githubusercontent.com/17736664/102157492-8fa92c00-3eba-11eb-834a-67892e070755.png)

我咋使用./install.sh --mphp_ver 80安装多一个php版本的时候报错了，请问要如果添加多一个PHP版本呢
openSSL already installed!
tar (child): libiconv-1.16.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 19: pushd: libiconv-1.16: No such file or directory
include/php-8.0.sh: line 20: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
tar (child): libzip-1.2.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 67: pushd: libzip-1.2.0: No such file or directory
include/php-8.0.sh: line 68: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
tar (child): php-8.0.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 101: pushd: php-8.0.0: No such file or directory
make: *** No rule to make target `clean'.  Stop.
include/php-8.0.sh: line 118: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
cat install.sh >install
chmod a+x install
PHP install failed, Please Contact the author!
Killed
[root@localhost oneinstack]# /bin/cp: cannot stat ‘php.ini-production’: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
Redirecting to /bin/systemctl start php-fpm.service
include/php-8.0.sh: line 285: popd: directory stack empty
include/php-8.0.sh: line 287: popd: directory stack empty

**Comment by oneinstack** [comment]
libiconv-1.16.tar.gz libzip-1.2.0.tar.gz 依赖被删掉了吗？
提前下载放到oneinstack/src目录下
http://mirrors.linuxeye.com/oneinstack/src/libiconv-1.16.tar.gz
http://mirrors.linuxeye.com/oneinstack/src/libiconv-1.16.tar.gz

**Comment by 449134904** [comment]
你好。我是没有删除的，我是之前安装的 oneinstack ，通过升级的方式更新了 oneinstack 的，我发现src确实是确实了libiconv-1.16.tar.gz这个文件 但是我查看了所有的服务器升级后的都是确实了libiconv-1.16.tar.gz

**Comment by 449134904** [comment]
![图片](https://user-images.githubusercontent.com/17736664/102159708-0b0cdc80-3ebf-11eb-843e-8e750988ef71.png)
下载后安装还是有问题

**Comment by 449134904** [comment]
ln -f /usr/local/share/man/man3/zip_open.3 /usr/local/share/man/man3/zip_open_from_source.3
ln -f /usr/local/share/man/man3/zip_stat.3 /usr/local/share/man/man3/zip_stat_index.3
ln -f /usr/local/share/man/man3/zip_source_function.3 /usr/local/share/man/man3/zip_source_function_create.3
ln -f /usr/local/share/man/man3/zip_file_strerror.3 /usr/local/share/man/man3/zip_strerror.3
ln -f /usr/local/share/man/man3/zip_source_win32a.3 /usr/local/share/man/man3/zip_source_win32a_create.3
ln -f /usr/local/share/man/man3/zip_source_win32handle.3 /usr/local/share/man/man3/zip_source_win32handle_create.3
ln -f /usr/local/share/man/man3/zip_source_win32w.3 /usr/local/share/man/man3/zip_source_win32w_create.3
make[3]: Leaving directory `/root/oneinstack/src/libzip-1.2.0/man'
make[2]: Leaving directory `/root/oneinstack/src/libzip-1.2.0/man'
make[1]: Leaving directory `/root/oneinstack/src/libzip-1.2.0/man'
Making install in src
make[1]: Entering directory `/root/oneinstack/src/libzip-1.2.0/src'
make[2]: Entering directory `/root/oneinstack/src/libzip-1.2.0/src'
 /bin/mkdir -p '/usr/local/bin'
  /bin/sh ../libtool   --mode=install /bin/install -c zipcmp zipmerge ziptool '/usr/local/bin'
libtool: install: /bin/install -c .libs/zipcmp /usr/local/bin/zipcmp
libtool: install: /bin/install -c .libs/zipmerge /usr/local/bin/zipmerge
libtool: install: /bin/install -c .libs/ziptool /usr/local/bin/ziptool
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/root/oneinstack/src/libzip-1.2.0/src'
make[1]: Leaving directory `/root/oneinstack/src/libzip-1.2.0/src'
Making install in regress
make[1]: Entering directory `/root/oneinstack/src/libzip-1.2.0/regress'
make[2]: Entering directory `/root/oneinstack/src/libzip-1.2.0/regress'
not installing shared objects needed only for testing
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/root/oneinstack/src/libzip-1.2.0/regress'
make[1]: Leaving directory `/root/oneinstack/src/libzip-1.2.0/regress'
Making install in examples
make[1]: Entering directory `/root/oneinstack/src/libzip-1.2.0/examples'
make[2]: Entering directory `/root/oneinstack/src/libzip-1.2.0/examples'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/root/oneinstack/src/libzip-1.2.0/examples'
make[1]: Leaving directory `/root/oneinstack/src/libzip-1.2.0/examples'
make[1]: Entering directory `/root/oneinstack/src/libzip-1.2.0'
make[2]: Entering directory `/root/oneinstack/src/libzip-1.2.0'
make[2]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/usr/local/lib/pkgconfig'
 /bin/install -c -m 644 libzip.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory `/root/oneinstack/src/libzip-1.2.0'
make[1]: Leaving directory `/root/oneinstack/src/libzip-1.2.0'
tar (child): php-8.0.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
include/php-8.0.sh: line 101: pushd: php-8.0.0: No such file or directory
make: *** No rule to make target `clean'.  Stop.
include/php-8.0.sh: line 118: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
PHP install failed, Please Contact the author!
Killed
[root@localhost oneinstack]# /bin/cp: cannot stat ‘php.ini-production’: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
sed: can't read /usr/local/php80/etc/php.ini: No such file or directory
Redirecting to /bin/systemctl start php-fpm.service

**Comment by 449134904** [comment]
checking size of long... (cached) 8
checking if we're at 64-bit platform... yes
checking for iconv support... yes
checking for iconv... yes
checking if iconv is glibc's... yes
checking if iconv supports errno... no
configure: error: iconv does not support errno
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
PHP install failed, Please Contact the author!
Killed

**Comment by SKIYET** [comment]
我也遇到同样的问题了

checking if iconv supports errno... no
configure: error: iconv does not support errno
make: *** No targets specified and no makefile found. Stop.
make: *** No rule to make target `install'. Stop.
PHP install failed, Please Contact the author!
Killed

@oneinstack 系统是debian10 64位 最新 vps 2c 2g

**Comment by channel168** [comment]
全新安装遇到过。

临时解决：
~/oneinstack/include/php-8.0.sh
去掉
--with-iconv-dir=${libiconv_install_dir}

**Comment by oneinstack** [comment]
fixed

**Comment by feelkiller** [comment]
not fixed, 使用 install mphp_ver 80安装依然报错：iconv does not support errno

**Comment by xjaqil** [comment]
~/oneinstack/include/php-8.1.sh
中
--with-iconv 
改成 
--with-iconv=${libiconv_install_dir}
再 
./install.sh

**Comment by lucki-cn** [comment]
还没有修复，环境Debian11，系统全新，php8.x安装依旧会有iconv does not support errno的错误提示。
解决办法：在
`export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/:$PKG_CONFIG_PATH` 
上面添加
`export LDFLAGS="$LDFLAGS -liconv"`

**Comment by sunmingyang** [comment]
问题依然存在 Ubuntu  20.04 64位 checking if iconv supports errno... no

**Comment by soulincomehere** [comment]
> 问题依然存在 Ubuntu 20.04 64位 checking if iconv supports errno... no

wsl2 ubuntu 20.04.01 64位 遇到同样的问题，不知道老哥有没有解决

**Comment by soulincomehere** [comment]
> 

在ubuntu20 64位版本中使用了这么办法，没有解决问题

**Comment by 449134904** [comment]
~/oneinstack/include/php-8.1.sh
中
--with-iconv
改成
--with-iconv=${libiconv_install_dir}
再
./install.sh

**Comment by soulincomehere** [comment]
> ~/oneinstack/include/php-8.1.sh 中 --with-iconv 改成 --with-iconv=${libiconv_install_dir} 再 ./install.sh

您这边的环境是ubuntu吗，我尝试过 这种方法 --with-iconv=${libiconv_install_dir}。

具体配置信息如下：
./configure \
--prefix=/usr/local/soft/php81 \
--with-config-file-path=/usr/local/soft/php81/etc \
--with-curl \
--with-freetype \
--enable-gd \
--with-jpeg \
--with-kerberos \
--with-libdir=lib64 \
--with-iconv=/usr/bin/libiconv \
--with-libxml \
--with-mysqli \
--with-openssl \
--with-pdo-mysql \
--with-pdo-sqlite \
--with-pear \
--enable-sockets \
--with-mhash \
--with-ldap-sasl \
--with-xsl \
--with-zlib \
--with-zip \
-with-bz2 \
--enable-fpm \
--enable-pdo \
--enable-ftp \
--enable-bcmath \
--enable-mbregex \
--enable-mbstring \
--enable-opcache \
--enable-pcntl \
--enable-shmop \
--enable-soap \
--enable-sockets \
--enable-sysvsem \
--enable-xml \
--enable-sysvsem \
--enable-cli \
--enable-opcache \
--enable-intl \
--enable-calendar \
--enable-static \
--enable-mysqlnd

**Comment by soulincomehere** [comment]
> > ~/oneinstack/include/php-8.1.sh 中 --with-iconv 改成 --with-iconv=${libiconv_install_dir} 再 ./install.sh
> 
> 您这边的环境是ubuntu吗，我尝试过 这种方法 --with-iconv=${libiconv_install_dir}。
> 
> 具体配置信息如下： ./configure --prefix=/usr/local/soft/php81 --with-config-file-path=/usr/local/soft/php81/etc --with-curl --with-freetype --enable-gd --with-jpeg --with-kerberos --with-libdir=lib64 --with-iconv=/usr/bin/libiconv --with-libxml --with-mysqli --with-openssl --with-pdo-mysql --with-pdo-sqlite --with-pear --enable-sockets --with-mhash --with-ldap-sasl --with-xsl --with-zlib --with-zip -with-bz2 --enable-fpm --enable-pdo --enable-ftp --enable-bcmath --enable-mbregex --enable-mbstring --enable-opcache --enable-pcntl --enable-shmop --enable-soap --enable-sockets --enable-sysvsem --enable-xml --enable-sysvsem --enable-cli --enable-opcache --enable-intl --enable-calendar --enable-static --enable-mysqlnd

checking whether to enable JIS-mapped Japanese font support in GD... no
checking for fabsf... yes
checking for floorf... yes
checking for zlib... yes
checking for libpng... yes
checking for libjpeg... yes
checking for freetype2... yes
checking for GNU gettext support... no
checking for GNU MP support... no
checking for mhash support... yes
checking size of long... (cached) 8
checking if we're at 64-bit platform... yes
checking for iconv support... yes
configure: error: Please reinstall the iconv library.
